#ifndef _TMW_LANG_TR_H
#define _TMW_LANG_TR_H

#define CANTCREATEHOMEDIR " gerekli fakat oluþturulamýyor. Çýkýlýyor!"
#define SDLINIT "SDL baþlatýlýyor..."
#define SDLCANTINIT "SDL baþlatýlamýyor : "
#define CANTSETHOME " ana dizin ayarlanamýyor. Çýkýlýyor!"
#define CANTSETUPDATES " dizini oluþturulamýyor. Çýkýlýyor!"
#define CANTFINDRESOURCE " kaynak klasörü bulunamýyor.\n"
#define INITCONFIG "Ayarlamalar baþlýyor..."
#define CANTCRATECONFIGPATH configPath << "oluþturulamadý " << ". Varsayýlan ayarlar kullanýlýyor."
#define VIDEOMODEERR "x: " << width << "Y:" << height << "Çözünürlük" << bpp << " olarak ayarlanamadý "
#define WARNINGS "Dikkat: %s"
#define HS0 "tmw" << std::endl << std::endl
#define HS1         << "Options: " << std::endl
#define HS2         << "  -h --help       : Display this help" << std::endl
#define HS3         << "  -v --version    : Display the version" << std::endl
#define HS4         << "  -u --skipupdate : Skip the update process" << std::endl
#define HS5         << "  -U --username   : Login with this username" << std::endl
#define HS6         << "  -P --password   : Login with this password" << std::endl
#define HS7         << "  -D --default    : Bypass the login process with default settings" << std::endl
#define HS8         << "  -p --playername : Login with this player" << std::endl
#define HS9         << "  -C --configfile : Configuration file to use"
#define HELPSCREEN HS0 HS1 HS2 HS3 HS4 HS5 HS6 HS7 HS8 HS9
#define TMWVERSION "ElektroGame versiyon "
#define TRYACCSERV "Hesap sunucusuna baðlanmayý deniyor..."
#define USERNAMES "Kullanýcý adi: %s"
#define TRYCHARSERV "Karakter sunucusuna baðlanmayý deniyor..."
#define MEMOCHAR "Seçilen karakter %s"
#define TRYMAPSERV "MAP sunucuna baðlanmayý deniyor..."
#define MAPS "Harita: %s"
#define DISCONNECT "Sunucuyla baðlantý kesildi!"
#define STATELOADDATA "Durum: Data yükleme."
#define STATELOGIN "Durum: LOGIN"
#define STATEREGISTER "Durum: REGISTER"
#define STATECHARSERVER "Durum: CHAR_SERVER"
#define STATECHARSELECT "Durum: CHAR_SELECT"
#define STATEGAME "Durum: GAME"
#define STATEUPDATE "Durum: UPDATE"
#define STATEERROR "Durum: ERROR"
#define ERROR "Hata"
#define STATECONNECT "Durum: CONNECTING"
#define CONNECTMAP "Map sunucusuna baðlanýyor..."
#define CONNECTCHAR "Karakter sunucusuna baðlanýyor..."
#define CONNECTACCOUNT "Hesap sunucusuna baðlanýyor..."
#define STATEEXIT "State: EXIT"
#define NOCONFIGFILE "Uyarý: Config dosyasý bulunamadý (%s)"
#define CONFOPENERR "Configuration::write() %s dosyasý yazma için acýlamadý."
#define CONFCREATEERR "Configuration::write() yazma amacýyla oluþturulamadý."
#define CONFWRITE "Configuration::write() ayarlar yazýlýyor..."
#define SCREENSAVE "Ekranýn görüntüsü kaydedildi:"
#define SCREENSAVEERR "Ekran görüntüsü kaydedilemedi!"
#define SUREQUIT "Oyundan çýkmak istediðinize emin misiniz?"
#define QUIT "Çýkýþ"
#define GUICHANERR "Dikkat: guichan hata üretti: %s"
#define SETVIDEOMODE "Ekran modu ayarlandý: %dx%d %s",w, h, fs ? "Tam ekran" : "Pencere"
#define USEVIDEODRVS "Kullanýlan ekran sunucusu: %s"
#define USEVIDEODRVNON "Kullanýlan ekran sürücüsü: bilinmiyor"
#define VIHWAVAILABLE "Possible to create hardware surfaces: %s",((vi->hw_available) ? "evet" : "hayýr")
#define VIVMAVAILABLE "Window manager available: %s",((vi->wm_available) ? "evet" : "hayýr")
#define VIBLITHW "Accelerated hardware to hardware blits: %s",((vi->blit_hw) ? "evet" : "hayýr")
#define VIBLITHWCC "Accelerated hardware to hardware colorkey blits: %s", ((vi->blit_hw_CC) ? "evet" : "hayýr")
#define VIBLITHWA "Accelerated hardware to hardware alpha blits: %s",((vi->blit_hw_A) ? "evet" : "hayýr")
#define VILITSW "Accelerated software to hardware blits: %s",((vi->blit_sw) ? "yes" : "no")
#define VIBLITSWCC "Accelerated software to hardware colorkey blits: %s",((vi->blit_sw_CC) ? "yes" : "no")
#define VIBLITSWA "Accelerated software to hardware alpha blits: %s",((vi->blit_sw_A) ? "yes" : "no")
#define VIBLITFILL "Accelerated color fills: %s",((vi->blit_fill) ? "yes" : "no")
#define VIVIDEOMEM "Available video memory: %d", vi->video_mem
#define LOGOPENERR "Dikkat :" << logFilename <<" dosyasý açýlýrken hata oluþtu.\n"
#define BTNOK "Tamam"
#define BTNCANCEL "Ýptal"
#define BTNYES "Evet"
#define BTNNO "Hayýr"
#define BTNCLOSE "Kapat"
#define CONFIRM "ONAY"
#define DELETECHAR "Bu karakteri silmek istediðinize emin misiniz?"
#define BTNNEW "Yeni"
#define BTNDELETE "Sil"
#define BTNPREV "Önceki"
#define BTNNEXT "Sonraki"
#define LBLNAME "Ýsim"
#define LBLLEVEL "Seviye"
#define LBLJOBL "Görev Sev"
#define LBLMONEY "Para"
#define LBLJOBL2 "Job Level: "
#define LBLMONEY2 "Gold: "
#define LBLNAME2 "Ýsim: "
#define CREATECHAR "Karakter Oluþturma"
#define HAIRCOLOR "Sac Rengi:"
#define HAIRSTYLE "Sac Stili:"
#define BTNCREATE "Oluþtur"
#define NAME4CHAR "Ýsim en az 4 karakter olmalý."
#define LBLPASS2 "Parola:"
#define LBLSERVER2 "Sunucu:"
#define BTNREGISTER "Kaydet"
#define LBLCONFIRM2 "Kontrol:"
#define BTNMALE "Erkek"
#define BTNFEMALE "Kýz"
#define ERRSHORTUSERNAME "Kullanýcý adi en az " << LEN_MIN_USERNAME << " uzunluðunda olmalý."
#define ERRLONGUSERNAME "Kullanýcý adi en fazla " << LEN_MAX_USERNAME << " karakter olabilir."
#define ERRSHORTPASS "Parola en az " << LEN_MIN_PASSWORD << " uzunluðunda olmalý."
#define ERRLONGPASS "Parola en fazla " << LEN_MAX_PASSWORD << " karakter olabilir."
#define ERRPASSMATCH "Parolalar tutarsýz."
#define LBLCONNECTING "Baðlanýyor..."
#define BTNPLAY "Oyna"
#define LBLCOMPLETED "Tamamlandý"
#define ERRACCESSDENIED "Eriþim Engellendi"
#define ERRNONID "Bu hesap kullanýlmýyor"
#define ERRUNKNOWN "Karakter seçiminde bilinmeyen hata"
#define ERRNAMEALREADDY "Karakter oluþturmada hata. Bu isim daha önceden alýnmýþ."
#define INFO "Bilgi"
#define PLAYERDELETED "Oyuncu silindi"
#define PlAYERCANTDELETE "Karakter silinemedi."
#define MAPSERVEROFF "Harita sunucu kapalý"
#define SPEEDHACK "Hýz hack tespit edildi"
#define DUPLICATEDLOGIN "Ýkinci giriþ"
#define UNKNOWN081 "Bilinmeyen hata: 0x0081"
#define UNREGISTEREDID "Kayýtlý olmayan ID"
#define WRONGPASS "Yanlýþ Parola"
#define ACCOUNTEXPIRED "Hesap suresi doldu"
#define REJECTEDSERVER "Sunucu tarafýndan reddedildiniz"
#define YOUBLOCKED "Yöneticiler tarafýndan bloke edildiniz"
#define YOUBANNED "5 dakikalýk giril yasaðý"
#define NAMEALREADYTAKEN "Bu isimde kullanýcý zaten mevcut"
#define UNKNOWNERR "Bilinmeyen hata"
#define LBLPRICE "Ücret: 0 GP / 0 GP"
#define BTNBUY "Satýn al"
#define LBLDESC2 "Açýklama :"
#define LBLDESC "Açýklama"
#define LBLEFFECT2 "Etki :"
#define LBLEFFECT "Etki"

#define UPDATING "Güncelleniyor..."
#define BUY "Satýn Al"
#define PRICEGP "Ücret: 0 GP / " + toString(mMoney)  + " GP"
#define PRICEGP2 "Ücret: " + toString(price)  + " GP / " \
                                + toString(mMoney) + " GP"
#define SHOP "Dükkan"
#define BTNSELL "sat"
#define SELECTCHARACTER "Karakter Seç"
#define SELECTSERVER "Sunucu Seç"
#define CHATLOGHELP "-- Yardým --"
#define CHATLOG1 "/help : Yardýmcý ekranýný göster."
#define CHATLOG2 "/announce : Genel duyuru (sadece yöneticiler)"
#define CHATLOG3 "/where : Harita ismini göster"
#define CHATLOG4 "/who : Çevrimiçi oyuncu sayýsýný göster"
#define CHATLOGUN "Bilinmeyen komut"

#define MSGBSKILL_TRADE "Alýþveriþ olmadý!"
#define MSGBSKILL_EMOTE "Duygu gösterilemedi!"
#define MSGBSKILL_SIT "Oturma gerçekleþemedi!"
#define MSGBSKILL_CREATECHAT "Sohbet yapýlamadý!"
#define MSGBSKILL_JOINPARTY "Partiye katýlamadýnýz!"
#define MSGBSKILL_SHOUT "Baðýramazsýnýz!"
#define MSGRFAIL_SKILLDEP " Henüz yeterli seviyeye gelmediniz!"
#define MSGRFAIL_INSUFHP " Insufficient HP!"
#define MSGRFAIL_INSUFSP " Insufficient SP!"
#define MSGRFAIL_NOMEMO " You have no memos!"
#define MSGRFAIL_SKILLDELAY " Bunu simdi yapamazsiniz!"
#define MSGRFAIL_ZENY " Seems you need more Zeny... ;-)"
#define MSGRFAIL_WEAPON " You cannot use this skill with that kind of weapon!"
#define MSGRFAIL_REDGEM " You need another red gem!"
#define MSGRFAIL_BLUEGEM " You need another blue gem!"
#define MSGRFAIL_OVERWEIGHT " You're carrying to much to do this!"
#define MSGDEF " Huh? What's that?"
#define MSGSKILL_WARP "Warp failed..."
#define MSGSKILL_STEAL "Could not steal anything..."
#define MSGSKILL_ENVENOM "Poison had no effect..."

#define DEBUG "Hata Gider"
#define DBGMUSICFILE "Müzik Dosyasý: "
#define DBGMINIMAP "Küçük harita : "
#define DBGPARTICLE "[Parçacýk Sayýsý: 0]"
#define EQUIPMENT "Ekipman"
#define HELP "Yardým"
#define INVENTORY "Aletler"
#define BTNUSE "Kullan"
#define BTNDROPE "Býrak"
#define TOTALMAXWEIGHT "Toplam Aðýrlýk: - Maksimum Aðýrlýk: "
#define TOTALWEIGHT "Toplam Aðýrlýk: "
#define MAXWEIGHT "Maksimum Aðýrlýk: "
#define SELECTAMOUNTITEMDROP "Býrakýlacak item miktarýný belirtin."
#define SELECTAMOUNTITEMTRADE "Alýþveriþte kullanýlacak item miktarýný belirtin."
#define LOGIN "Giriþ"
#define MINIMAP "Küçük Harita"
#define LBLNPC "Üstat"
#define MONEYTOTAL "Para: 0 GP / Toplam: 0 GP"
#define MONEYPLAYER "Para: 0 GP / Toplam: "+ toString(mPlayerMoney) + " GP"
#define MONEYPLAYER2 "Para: " + toString(price) + " GP / Toplam: " + toString(price + mPlayerMoney) + " GP"
#define LBLSETUP "Ayar"
#define BTNAPPLY "Uygula"
#define BTNRESETWINDOWS "Sýfýrla"
#define LBLVIDEO "Görüntü"
#define LBLAUDIO "Ses"
#define LBLJOYSTICK "Joystick"
#define LBLSFXVOLUME "Efekt sesi"
#define LBLMUSICVOLUME "Müzik sesi"
#define LBLSOUND "Ses Açýk"
#define LBLSTARTCALIB "Kalibrasyonu baþlatmak için düðmeye basýn."
#define BTNCALIBRATE "Kalibrasyon"
#define LBLANABLEJOYSTICK " Joystick Açýk"
#define LBLSTOP "Stop"
#define LBLROTATESTICK " Joystick dondurun"
#define LBLFULLSCREEN "Tam Ekran"
#define LBLCUSTOMCURSOR "Özel Ýmleç"
#define LBLFPSLIMIT2 "FPS Limiti: "
#define LBLSCROLLLAZINESS "Kayma yavaþlýðý"
#define LBLGUIOPACITY "Þeffaflýk"
#define LBLSCROLLRADIUS "Kayma Çapý"
#define LBLAMBIENTFX "Cevre Efekt"
#define LBLOFF "kapalý"
#define LBLLOW "düþük"
#define LBLHIGH "yüksek"
#define LBLSKILLS "Huner"
#define LBLSKILLPOINT2 "Huner Puaný:"
#define LBLSKILLPOINT2i "Huner Puaný: %i"
#define BTNUP "Art"
#define BTNUSE "Kullan"
#define LBLLEVEL2 "Seviye:"
#define LBLMONEY22 "Para:"
#define LBLSTATUS "Durum"
#define LBLHP2 "SP:"
#define LBLEXP2 "Tecrübe:"
#define LBLMP2 "Enerji Seviyesi:"
#define LBLJOB2 "Uzmanlýk:"
#define LBLSTATS "Ýstatistikler"
#define LBLTOTAL "Total"
#define LBLCOST "Ücret"
#define LBLATTACK "Atak:"
#define LBLDEFENSE "Savunma:"
#define LBLMATTACK "Genel Yetenek:"
#define LBLMDEFENSE "Kültür:"
#define LBLACCURACY "Teknik:"
#define LBLEVADE "Tecrübe:"
#define LBLREFLEX "Uzmanlýk:"
#define LBLREMAININGSTATUS "Kalan durum puaný: "
#define LBLSTRENGTH "Güç"
#define LBLAGILITY "Çeviklik"
#define LBLVITALITY "Dayanýklýlýk"
#define LBLINTELLIGENCE "Zeka"
#define LBLDEXTERITY "Ustalýk"
#define LBLLUCK "Þans"
#define LBLTRADEYOU "Alisveris"
#define BTNADD "Ekle"
#define BTNTRADE "Al Sat"
#define LBLYOUGET "Aldýn: 0z"
#define LBLYOUGET2 "Aldýn:"
#define LBLYOUGIVE "Verdin:"
#define FAILEDADDING "Eleman eklenemedi. Pencere bir tane daha ekleyemezsin."
#define BTNCHECK "Kontrol Et"
#define BTNREMOVE "Kaldýr"
#define LBLCALCULATOR "Hesap Mak."


#endif
